/** @type {import('../registry.js').ColorSetDefinition} */
export default {
  id: "flat-ui",
  name: "Flat UI",
  colors: [
    { hex: "#C0392B", name: "Pomegranate" },
    { hex: "#E74C3C", name: "Alizarin" },
    { hex: "#9B59B6", name: "Amethyst" },
    { hex: "#8E44AD", name: "Wisteria" },
    { hex: "#2980B9", name: "Belize Hole" },
    { hex: "#3498DB", name: "Peter River" },
    { hex: "#1ABC9C", name: "Turquoise" },
    { hex: "#16A085", name: "Green Sea" },
    { hex: "#27AE60", name: "Nephritis" },
    { hex: "#2ECC71", name: "Emerald" },
    { hex: "#F1C40F", name: "Sunflower" },
    { hex: "#F39C12", name: "Orange" },
    { hex: "#E67E22", name: "Carrot" },
    { hex: "#D35400", name: "Pumpkin" },
    { hex: "#ECF0F1", name: "Clouds" },
    { hex: "#BDC3C7", name: "Silver" },
    { hex: "#7F8C8D", name: "Concrete" },
    { hex: "#7F8C8D", name: "Asbestos" },
    { hex: "#34495E", name: "Wet Asphalt" },
    { hex: "#2C3E50", name: "Midnight Blue" },
  ],
};
