/** @type {import('../registry.js').ColorSetDefinition} */
export default {
  id: "material",
  name: "Material",
  colors: [
    { hex: "#F44336", name: "Red" },
    { hex: "#E91E63", name: "Pink" },
    { hex: "#9C27B0", name: "Purple" },
    { hex: "#673AB7", name: "Deep Purple" },
    { hex: "#3F51B5", name: "Indigo" },
    { hex: "#2196F3", name: "Blue" },
    { hex: "#03A9F4", name: "Light Blue" },
    { hex: "#00BCD4", name: "Cyan" },
    { hex: "#009688", name: "Teal" },
    { hex: "#4CAF50", name: "Green" },
    { hex: "#8BC34A", name: "Light Green" },
    { hex: "#CDDC39", name: "Lime" },
    { hex: "#FFEB3B", name: "Yellow" },
    { hex: "#FFC107", name: "Amber" },
    { hex: "#FF9800", name: "Orange" },
    { hex: "#FF5722", name: "Deep Orange" },
    { hex: "#795548", name: "Brown" },
    { hex: "#9E9E9E", name: "Grey" },
    { hex: "#607D8B", name: "Blue Grey" },
    { hex: "#FFFFFF", name: "White" },
    { hex: "#000000", name: "Black" },
  ],
};
