/** @type {import('../registry.js').ColorSetDefinition} */
export default {
  id: "tailwind",
  name: "Tailwind",
  colors: [
    { hex: "#FB2C36", name: "Red" },
    { hex: "#FF692A", name: "Orange" },
    { hex: "#FE9A37", name: "Amber" },
    { hex: "#F0B13B", name: "Yellow" },
    { hex: "#7CCF35", name: "Lime" },
    { hex: "#31C950", name: "Green" },
    { hex: "#37BC7D", name: "Emerald" },
    { hex: "#36BBA7", name: "Teal" },
    { hex: "#3BB8DB", name: "Cyan" },
    { hex: "#34A6F4", name: "Sky" },
    { hex: "#2B7FFF", name: "Blue" },
    { hex: "#615FFF", name: "Indigo" },
    { hex: "#8E51FF", name: "Violet" },
    { hex: "#AD46FF", name: "Purple" },
    { hex: "#E12AFB", name: "Fuchsia" },
    { hex: "#F6339A", name: "Pink" },
    { hex: "#FF2056", name: "Rose" },
    { hex: "#62748E", name: "Slate" },
    { hex: "#6A7282", name: "Gray" },
    { hex: "#71717B", name: "Zinc" },
    { hex: "#737373", name: "Neutral" },
    { hex: "#79716B", name: "Stone" },
  ],
};
