import assert from "node:assert/strict";
import { deflateSync } from "node:zlib";
import test from "node:test";

import { isBgcode, parseGcodeMeta } from "../app/components/gcode.js";

const textEncoder = new TextEncoder();

function concatBytes(...parts) {
  const total = parts.reduce((size, part) => size + part.length, 0);
  const output = new Uint8Array(total);
  let offset = 0;
  for (const part of parts) {
    output.set(part, offset);
    offset += part.length;
  }
  return output;
}

function buildMetadataBlock(type, text, compression = 0) {
  const uncompressed = textEncoder.encode(text);
  const payload = compression === 1 ? new Uint8Array(deflateSync(uncompressed)) : uncompressed;
  const headerBytes = compression === 0 ? 8 : 12;
  const block = new Uint8Array(headerBytes + 2 + payload.length);
  const view = new DataView(block.buffer);
  view.setUint16(0, type, true);
  view.setUint16(2, compression, true);
  view.setUint32(4, uncompressed.length, true);
  if (compression !== 0) view.setUint32(8, payload.length, true);
  view.setUint16(headerBytes, 0, true); // INI metadata encoding
  block.set(payload, headerBytes + 2);
  return block;
}

function buildBgcode(blocks) {
  const header = new Uint8Array(10);
  const view = new DataView(header.buffer);
  view.setUint32(0, 0x45444347, true); // GCDE
  view.setUint32(4, 1, true);
  view.setUint16(8, 0, true); // no block checksums
  return concatBytes(header, ...blocks);
}

test("parses Prusa-style G-code metadata comments", async () => {
  const source = [
    "; generated by PrusaSlicer 2.7.0",
    "; nozzle_diameter = 0.4",
    "; filament_type = PETG",
    "; layer_height = 0.2",
    "G1 X10 Y10 E0.2",
    "; estimated printing time (normal mode) = 1h 2m 3s",
    "; filament used [g] = 4.00",
    "; total filament used [g] = 4.74",
    "; filament used [mm] = 1590.68",
    "; filament used [cm3] = 3.83",
  ].join("\n");

  const metadata = await parseGcodeMeta(source);

  assert.equal(metadata.format, "gcode");
  assert.equal(metadata.durationSec, 3723);
  assert.equal(metadata.filamentGrams, 4.74);
  assert.equal(metadata.filamentMm, 1590.68);
  assert.equal(metadata.filamentM, 1.59068);
  assert.equal(metadata.filamentCm3, 3.83);
  assert.equal(metadata.filamentType, "PETG");
  assert.equal(metadata.nozzleMm, 0.4);
  assert.equal(metadata.layerHeightMm, 0.2);
  assert.equal(metadata.slicer, "PrusaSlicer 2.7.0");
  assert.equal(metadata.raw.filament_used_g, "4.00");
});

test("parses Cura-style time and filament comments", async () => {
  const metadata = await parseGcodeMeta(
    ";TIME:1234\n;Filament used: 1.25m\n;LAYER_HEIGHT:0.2\nG1 X0 Y0"
  );

  assert.equal(metadata.durationSec, 1234);
  assert.equal(metadata.filamentMm, 1250);
  assert.equal(metadata.layerHeightMm, 0.2);
});

test("parses uncompressed bgcode metadata blocks", async () => {
  const bgcode = buildBgcode([
    buildMetadataBlock(
      0,
      "producer = PrusaSlicer\nproduced_on_2026_08_31_at_16 = 29:37 UTC\n"
    ),
    buildMetadataBlock(
      3,
      "nozzle_diameter = 0.4\nnozzle_high_flow = 1\nlayer_height = 0.25\n" +
        "variable_layer_height = 1\nfilament_retract_length = 0.8\n" +
        "bed_temperature = 85\nfill_density = 15%\ntemperature = 250\n" +
        "printer_model = MK4\nobjects_info = " +
        '{"objects":[{"name":"box.stl","polygon":[[0,0],[1,0],[1,1],[0,1]]}]}\n'
    ),
    buildMetadataBlock(
      4,
      "estimated_printing_time = 47m 27s\nslowdown_below_layer_time = 9\n" +
        "filament_load_time = 10.9\ntotal_filament_used_g = 12.5\n" +
        "filament_used_mm = 1393.34\nfilament_used_cm3 = 3.35\n" +
        "filament_ramming_volume = 10\nperimeters = 2\n" +
        "total_filament_used_for_wipe_tower_g = 0.75\n"
    ),
    buildMetadataBlock(2, "filament_type = PLA\nlayer_height = 0.15\n"),
  ]);

  assert.equal(isBgcode(bgcode), true);
  const metadata = await parseGcodeMeta(bgcode);

  assert.equal(metadata.format, "bgcode");
  assert.equal(metadata.timestamp, "2026-08-31 16:29:37 UTC");
  assert.equal(metadata.durationSec, 2847);
  assert.equal(metadata.filamentGrams, 12.5);
  assert.equal(metadata.filamentMm, 1393.34);
  assert.equal(metadata.filamentM, 1.39334);
  assert.equal(metadata.filamentCm3, 3.35);
  assert.equal(metadata.filamentType, "PLA");
  assert.equal(metadata.nozzleMm, 0.4);
  assert.equal(metadata.nozzleHighFlow, true);
  assert.equal(metadata.bedTemperatureC, 85);
  assert.equal(metadata.fillDensityPercent, 15);
  assert.equal(metadata.nozzleTemperatureC, 250);
  assert.equal(metadata.layerHeightMm, 0.15);
  assert.equal(metadata.perimeters, 2);
  assert.equal(metadata.wipeTowerFilamentGrams, 0.75);
  assert.equal(metadata.objectCount, 1);
  assert.equal(metadata.objects[0].name, "box.stl");
  assert.equal(metadata.printerModel, "MK4");
  assert.equal(metadata.slicer, "PrusaSlicer");
  assert.equal(metadata.raw["printer.nozzle_diameter"], "0.4");
});

test("parses Deflate-compressed bgcode metadata", async (t) => {
  if (typeof DecompressionStream !== "function") {
    t.skip("DecompressionStream is unavailable");
    return;
  }

  const bgcode = buildBgcode([
    buildMetadataBlock(4, "estimated_printing_time = 2m 5s\n", 1),
  ]);
  const metadata = await parseGcodeMeta(bgcode);

  assert.equal(metadata.durationSec, 125);
  assert.deepEqual(metadata.warnings, []);
});

test("returns null fields and warnings for empty or truncated input", async () => {
  const empty = await parseGcodeMeta("");
  assert.equal(empty.format, "gcode");
  assert.equal(empty.durationSec, null);
  assert.match(empty.warnings[0], /empty/i);

  const truncated = await parseGcodeMeta(
    new Uint8Array([0x47, 0x43, 0x44, 0x45, 1, 0, 0, 0, 0, 0, 1])
  );
  assert.equal(truncated.format, "bgcode");
  assert.equal(truncated.durationSec, null);
  assert.match(truncated.warnings[0], /truncated/i);
});

test("does not interpret motion lines as metadata", async () => {
  const metadata = await parseGcodeMeta("G1 X10 Y10 E1 = not metadata\nM117 TIME:99");
  assert.equal(metadata.durationSec, null);
  assert.deepEqual(metadata.raw, {});
});
