import { initShell } from "./shell/shell.js";
import { setStickyHeader, setStickySectionHeadings } from "./shell/sticky.js";
import { setTitleNumbering } from "./shell/title-numbering.js";
import { initDialog } from "./components/dialog.js";
import { initAboutDialog } from "./components/about-dialog.js";
import { initCombobox } from "./components/combobox.js";
import { initCombo } from "./components/combo.js";
import { initDropdown } from "./components/dropdown.js";
import { initToggleDropdown } from "./components/dropdown-toggle.js";
import { initExpands } from "./components/expand.js";
import { initAccordion } from "./components/accordion.js";
import { initTabs } from "./components/tabs.js";
import { initCodeBlocks } from "./components/code-block.js";
import { initExpandableSurfaces } from "./components/expandable-surface.js";
import { showBanner, hideBanner } from "./components/banner.js";
import {
  flashTooltip,
  showPersistentTooltip,
  dismissPersistentTooltip,
} from "./components/tooltip.js";
import { copyText } from "./utils/clipboard.js";
import {
  prepareButtonLabelFlash,
  setButtonLabelFlash,
  flashButtonLabel,
} from "./utils/button-label.js";
import { initPopover } from "./components/popover.js";
import { initTutorial } from "./components/tutorial.js";
import { initFileDropzone } from "./components/file-dropzone.js";
import { initFileDownload } from "./components/file-download.js";
import { initImagePreview } from "./components/image-preview.js";
import { initDatePicker } from "./components/date-picker/index.js";
import { initTimePicker } from "./components/time-picker.js";
import { initDurationInput } from "./components/duration-input.js";
import { initSlider } from "./components/slider.js";
import { initStepper } from "./components/stepper.js";
import { initColorInput } from "./components/color-input.js";
import { initColorSet } from "./components/color-set/index.js";
import { initColorPicker } from "./components/color-picker/index.js";
import { initToggle } from "./components/toggle.js";
import { initToggleButtons } from "./components/toggle-button.js";
import { initTriStateCheckbox } from "./components/checkbox.js";
import { initSegmentedControl } from "./components/segmented-control.js";
import { initPagination } from "./components/pagination.js";
import { initProgressBar } from "./components/progress-bar.js";
import { initSpinner } from "./components/spinner.js";
import { initProgressIndicator } from "./components/progress-indicator.js";
import { initRichTextEditor } from "./components/rich-text-editor.js";
import { initChart } from "./components/charts.js";
import { defineChart } from "./vendor/tanstack-charts/scene.js";
import { barY } from "./vendor/tanstack-charts/bar.js";
import { tooltip } from "./vendor/tanstack-charts/tooltip.js";
import { scaleBand } from "./vendor/tanstack-charts/scales/band.js";
import { scaleLinear } from "./vendor/tanstack-charts/scales/linear.js";
import { initDiagrams } from "./components/diagram.js";
import { initTable } from "./components/table.js";
import { initTabularInput } from "./components/tabular-input.js";
import { initBadge } from "./components/badge.js";
import { initChipGroup, initChipInput } from "./components/chip.js";
import { initLegend } from "./components/legend.js";
import { setHidden } from "./utils/dom.js";

initShell();
initExpands(document);
initTabs(document);
const codeBlockInstances = initCodeBlocks(document);

const demoImagePreview = initImagePreview(
  document.getElementById("demo-image-preview")
);

initExpandableSurfaces(document);

const demoCodeBlock = codeBlockInstances[0] ?? null;

initSegmentedControl(document.getElementById("demo-code-mode"), {
  onChange: ({ value }) => {
    demoCodeBlock?.setMode(value);
  },
});

initSegmentedControl(document.getElementById("demo-code-toolbar"), {
  onChange: ({ value }) => {
    demoCodeBlock?.setToolbarPosition(value);
  },
});

function buildDemoTextFile(title) {
  return [
    title,
    "================",
    "",
    "Generated by the SMA1 Framework demo.",
    `Created: ${new Date().toLocaleString()}`,
    "",
    "Replace this with your own export logic.",
  ].join("\n");
}

initRichTextEditor(document.getElementById("demo-rich-text-editor-block"));

const demoFruitSales = [
  { fruit: "Apples", sold: 42 },
  { fruit: "Bananas", sold: 28 },
  { fruit: "Cherries", sold: 35 },
  { fruit: "Dates", sold: 19 },
  { fruit: "Elderberries", sold: 31 },
];

/** Match `.charts` `--charts-tick-size` (0.8125rem ≈ 13px) for layout. */
const DEMO_CHART_TICK_FONT_SIZE = 13;

initChart(document.getElementById("demo-bar-chart"), {
  definition: defineChart({
    marks: [
      barY(demoFruitSales, {
        id: "fruit-sales",
        x: "fruit",
        y: "sold",
        fill: "var(--accent)",
      }),
    ],
    x: {
      scale: () => scaleBand().padding(0.18),
      axis: {
        label: "Fruit",
        tickLabels: { fontSize: DEMO_CHART_TICK_FONT_SIZE },
      },
    },
    y: {
      scale: scaleLinear,
      nice: true,
      grid: true,
      axis: {
        label: "Sold",
        tickLabels: { fontSize: DEMO_CHART_TICK_FONT_SIZE },
      },
    },
    tooltip,
  }),
  ariaLabel: "Example fruit sales",
});

initDiagrams(document);

initFileDropzone(document.getElementById("demo-file-dropzone-single"));

initFileDropzone(document.getElementById("demo-file-dropzone-multi"));

initFileDownload(document.getElementById("demo-file-download"), {
  files: [
    {
      filename: "hello.txt",
      getContent: () => buildDemoTextFile("Hello"),
    },
    {
      filename: "notes.txt",
      getContent: () => buildDemoTextFile("Notes"),
    },
    {
      filename: "summary.txt",
      getContent: () => buildDemoTextFile("Summary"),
    },
  ],
});

fetch(new URL("./res/demo-image-preview.svg", import.meta.url))
  .then((response) => response.text())
  .then((markup) => {
    demoImagePreview?.setSvg(markup);
  });

initDatePicker(document.getElementById("demo-date-picker"));
initDatePicker(document.getElementById("demo-date-picker-time"));
initTimePicker(document.getElementById("demo-time-picker"));
initTimePicker(document.getElementById("demo-time-picker-seconds"));
initDurationInput(document.getElementById("demo-duration-input"));

initSlider(document.getElementById("demo-slider-integer"));

initStepper(document.getElementById("demo-stepper"));

initColorInput(document.getElementById("demo-color-input"));
initColorInput(document.getElementById("demo-color-input-empty"));
initColorInput(document.getElementById("demo-color-input-alpha"));
initColorInput(document.getElementById("demo-color-input-set"));
initColorInput(document.getElementById("demo-color-input-picker"));
initColorSet(document.getElementById("demo-color-set-embedded"));
initColorPicker(document.getElementById("demo-color-picker-embedded"));

initProgressIndicator(document.getElementById("demo-progress-indicator"));
initProgressIndicator(document.getElementById("demo-progress-indicator-vertical"));

initAccordion(document.getElementById("demo-accordion"));

initTriStateCheckbox(document.getElementById("demo-checkbox-tristate"));

initToggle(document.getElementById("demo-toggle-off"));
initToggle(document.getElementById("demo-toggle-on"));
initToggle(document.getElementById("demo-toggle-tristate"));
initToggle(document.getElementById("demo-toggle-disabled"));
initToggle(document.getElementById("demo-toggle-slim-off"));
initToggle(document.getElementById("demo-toggle-slim-on"));

initSegmentedControl(document.getElementById("demo-segmented-view"));
initSegmentedControl(document.getElementById("demo-segmented-slim"));

const demoChipFilterResults = document.getElementById("demo-chip-filter-results");

function syncChipFilterList(values) {
  if (!demoChipFilterResults) return;
  const selected = new Set(values);
  const items = [...demoChipFilterResults.querySelectorAll("[data-chip-category]")];
  for (const item of items) {
    const show = selected.size === 0 || selected.has(item.dataset.chipCategory);
    item.hidden = !show;
  }
}

initChipGroup(document.getElementById("demo-chip-filters"), {
  onChange: ({ values }) => syncChipFilterList(values),
});
syncChipFilterList(
  [...document.querySelectorAll("#demo-chip-filters .chip[aria-pressed='true']")].map(
    (chip) => chip.dataset.chipValue
  )
);

initChipInput(document.getElementById("demo-chip-input"));

initLegend(document.getElementById("demo-legend"));

initSegmentedControl(document.getElementById("demo-segmented-panels"));
initPagination(document.getElementById("demo-pagination"));

initTable(document.getElementById("demo-table"));

initTabularInput(document.getElementById("demo-tabular-input"), {
  columns: [
    { id: "name", label: "Name", type: "text" },
    { id: "sku", label: "SKU", type: "text" },
    { id: "qty", label: "Qty", type: "number" },
    { id: "price", label: "Price", type: "number" },
    { id: "category", label: "Category", type: "text" },
    { id: "supplier", label: "Supplier", type: "text" },
    { id: "active", label: "Active", type: "logical" },
  ],
  rows: [
    {
      id: "r1",
      cells: {
        name: "Widget",
        sku: "W-100",
        qty: 12,
        price: 9.5,
        category: "Parts",
        supplier: "Acme",
        active: true,
      },
    },
    {
      id: "r2",
      cells: {
        name: "Gadget",
        sku: "G-200",
        qty: 3,
        price: 24,
        category: "Tools",
        supplier: "Globex",
        active: false,
      },
    },
    {
      id: "r3",
      cells: {
        name: "Doohickey",
        sku: "D-300",
        qty: 7,
        price: 15.25,
        category: "Parts",
        supplier: "Acme",
        active: true,
      },
    },
  ],
});

const demoProgressPanels = document.getElementById("demo-progress-panels");
const demoProgressVariantTriggerLabel = document
  .querySelector("#demo-progress-bar-variants-trigger .dropdown-trigger-label");

initDropdown(document.getElementById("demo-progress-bar-variants"), {
  onSelect: ({ label, item }) => {
    if (demoProgressVariantTriggerLabel && label) {
      demoProgressVariantTriggerLabel.textContent = label;
    }
    const panelId = item?.dataset.panel;
    if (!demoProgressPanels || !panelId) return;
    for (const panel of demoProgressPanels.children) {
      setHidden(panel, panel.id !== panelId);
    }
  },
});

initProgressBar(document.getElementById("demo-progress-bar"));
initProgressBar(document.getElementById("demo-progress-bar-percent"));
initProgressBar(document.getElementById("demo-progress-bar-fraction"));
initProgressBar(document.getElementById("demo-progress-bar-error"));
initProgressBar(document.getElementById("demo-progress-bar-disabled"));
initProgressBar(document.getElementById("demo-progress-bar-indeterminate"));
initProgressBar(document.getElementById("demo-progress-bar-bounce"));

const demoSpinnerHost = initSpinner(document.getElementById("demo-spinner-host"));

document.getElementById("demo-spinner-load")?.addEventListener("click", () => {
  if (demoSpinnerHost?.isVisible()) return;
  demoSpinnerHost?.show();
  window.setTimeout(() => {
    demoSpinnerHost?.hide();
  }, 2000);
});

const comboOptions = [
  { value: "example-1", label: "Example 1" },
  { value: "example-2", label: "Example 2" },
  { value: "example-3", label: "Example 3" },
];

function pickRandomOption(options, excludeValue) {
  const pool = excludeValue
    ? options.filter((option) => option.value !== excludeValue)
    : options;
  if (!pool.length) return options[0];
  return pool[Math.floor(Math.random() * pool.length)];
}

let lastComboValue = null;

initCombobox(document.getElementById("demo-combobox"));
initCombobox(document.getElementById("demo-combobox-multi"));

initCombo(document.getElementById("demo-combo"), {
  onMainClick: () => {
    const picked = pickRandomOption(comboOptions, lastComboValue);
    lastComboValue = picked.value;
  },
  onSelect: ({ value }) => {
    lastComboValue = value;
  },
});

initDropdown(document.getElementById("demo-dropdown"));
initDropdown(document.getElementById("demo-dropdown-icons"));
initToggleDropdown(document.getElementById("demo-toggle-dropdown"));

initToggleButtons(document);

document.getElementById("demo-tooltip-flash-success")?.addEventListener("click", (e) => {
  const btn = e.currentTarget;
  if (!(btn instanceof HTMLElement)) return;
  flashTooltip(btn, { text: "Copied", tone: "success" });
});

document.getElementById("demo-tooltip-flash-error")?.addEventListener("click", (e) => {
  const btn = e.currentTarget;
  if (!(btn instanceof HTMLElement)) return;
  flashTooltip(btn, { text: "Failed to copy", tone: "error" });
});

async function demoLabelFlashClick(button) {
  if (!(button instanceof HTMLButtonElement)) return;
  const ok = await copyText("demo");
  flashButtonLabel(button, ok, {
    reset: () => {
      button.setAttribute("aria-label", "Copy");
      setButtonLabelFlash(button, "Copy");
    },
  });
}

const demoLabelFlashShift = document.getElementById("demo-label-flash-shift");
const demoLabelFlashFixed = document.getElementById("demo-label-flash-fixed");
demoLabelFlashShift?.setAttribute("aria-label", "Copy");
demoLabelFlashFixed?.setAttribute("aria-label", "Copy");
prepareButtonLabelFlash(demoLabelFlashFixed, { idle: "Copy" });
demoLabelFlashShift?.addEventListener("click", (e) => {
  void demoLabelFlashClick(e.currentTarget);
});
demoLabelFlashFixed?.addEventListener("click", (e) => {
  void demoLabelFlashClick(e.currentTarget);
});

/** @type {string | null} */
let demoPersistentTipId = null;
const demoPersistentTarget = document.getElementById("demo-tooltip-persistent-dismiss");

document.getElementById("demo-tooltip-persistent")?.addEventListener("click", () => {
  if (!(demoPersistentTarget instanceof HTMLElement)) return;
  if (demoPersistentTipId) {
    dismissPersistentTooltip(demoPersistentTipId);
  }
  demoPersistentTipId = showPersistentTooltip(demoPersistentTarget, {
    text: "Click this button to dismiss",
    tone: "info",
    position: "top",
  });
});

demoPersistentTarget?.addEventListener("click", () => {
  if (demoPersistentTipId) {
    dismissPersistentTooltip(demoPersistentTipId);
    demoPersistentTipId = null;
  }
});

const demoPopoverAnchor = document.getElementById("demo-popover-anchor");
const demoPopover = initPopover({
  anchor: demoPopoverAnchor,
  title: "Popover",
  body: "A speech bubble with a notch aimed at the anchor. Use this for richer tips than a tooltip.",
  position: "top",
  actions: [
    {
      label: "Got it",
      className: "btn btn-primary",
    },
  ],
});

document.getElementById("demo-popover-open")?.addEventListener("click", () => {
  if (demoPopover?.isOpen()) demoPopover.close();
  else demoPopover?.open();
});

/* Anchor is the pointed-at control; clicking it also toggles the popover. */
demoPopoverAnchor?.addEventListener("click", () => {
  if (demoPopover?.isOpen()) demoPopover.close();
  else demoPopover?.open();
});

const overviewTour = initTutorial({
  id: "demo-overview",
  startTriggers: "#demo-tutorial-overview",
  steps: [
    {
      title: "Overview tour",
      body: "This script walks the Information & prompts area using real controls — no extra demo targets.",
    },
    {
      target: "#demo-info-prompts",
      title: "This section",
      body: "Tutorials can spotlight a whole section. Everything outside stays dimmed.",
      position: "bottom",
    },
    {
      target: "#demo-tutorials-panel",
      title: "Tutorials",
      body: "Or zoom in on a panel. These buttons start the overview, interactive, and branching tours.",
      position: "left",
    },
    {
      target: "#demo-popovers-panel",
      title: "Popovers",
      body: "Show popover opens a speech bubble aimed at Anchor target.",
      position: "right",
    },
    {
      target: "#demo-tutorial-interactive",
      title: "Interactive tour",
      body: "Try the other tour next — it lets you click a real control to advance.",
      position: "top",
    },
  ],
});

initTutorial({
  id: "demo-interactive",
  startTriggers: "#demo-tutorial-interactive",
  steps: [
    {
      title: "Interactive tour",
      body: "Most steps stay blocked. The next one lets you use the highlighted control.",
    },
    {
      target: "#demo-popover-anchor",
      title: "Try the anchor",
      body: "Click Anchor target to advance. That also opens the popover.",
      position: "top",
      interactive: true,
      advanceOn: "click",
    },
    {
      target: "#demo-popover-open",
      title: "Show popover",
      body: "You can open the same bubble from this button. Press Done or Escape to finish.",
      position: "bottom",
    },
  ],
});

let tutorialPath = "a";

initCombo(document.getElementById("demo-tutorial-combo"), {
  onSelect: ({ value }) => {
    tutorialPath = value;
    const main = document.getElementById("demo-tutorial-combo-main");
    if (main) main.textContent = value === "b" ? "Option B" : "Option A";
  },
});

initTutorial({
  id: "demo-branching",
  startTriggers: "#demo-tutorial-branching",
  steps: [
    {
      target: "#demo-tutorial-branch",
      title: "Pick a path",
      body: "Open the chevron, choose Option A or Option B, then press Next. The following step depends on that choice.",
      position: "right",
      interactive: true,
    },
    {
      when: () => tutorialPath === "b",
      steps: [
        {
          target: "#demo-tutorial-path-b",
          title: "Option B",
          body: "This step is included only while Option B is selected.",
          position: "top",
        },
      ],
    },
    {
      when: () => tutorialPath !== "b",
      steps: [
        {
          target: "#demo-tutorial-path-a",
          title: "Option A",
          body: "This step is included when Option A is selected (the default).",
          position: "top",
        },
      ],
    },
    {
      target: "#demo-tutorials-panel",
      title: "Paths rejoin",
      body: "Unconditional steps after a branch run for every path. Press Done or Escape to finish.",
      position: "left",
    },
  ],
});

const demoBadge = initBadge(document.getElementById("demo-badge-host"));
document.getElementById("demo-badge-btn")?.addEventListener("click", () => {
  demoBadge?.increment();
});

const demoBadgeDot = initBadge(document.getElementById("demo-badge-dot-host"), {
  value: true,
});
document.getElementById("demo-badge-dot-btn")?.addEventListener("click", () => {
  const on = demoBadgeDot?.getValue();
  demoBadgeDot?.setValue(!on);
});

initToggle(document.getElementById("demo-sticky-header"), {
  onChange: ({ checked }) => {
    setStickyHeader(checked);
  },
});

initToggle(document.getElementById("demo-sticky-section-headings"), {
  onChange: ({ checked }) => {
    setStickySectionHeadings(checked);
  },
});

initToggle(document.getElementById("demo-title-numbering"), {
  onChange: ({ checked }) => {
    setTitleNumbering(checked);
  },
});

const ABOUT_HINT_STORAGE_KEY = "sma1-demo-about-hint-seen";
const aboutOpenBtn = document.getElementById("about-open-btn");

/** @type {ReturnType<typeof initPopover> | null} */
let aboutHintPopover = null;

function hasSeenAboutHint() {
  try {
    return localStorage.getItem(ABOUT_HINT_STORAGE_KEY) === "1";
  } catch {
    return true;
  }
}

function markAboutHintSeen() {
  try {
    localStorage.setItem(ABOUT_HINT_STORAGE_KEY, "1");
  } catch {
    /* ignore quota / private mode */
  }
}

function dismissAboutHint() {
  if (!aboutHintPopover) return;
  const popover = aboutHintPopover;
  aboutHintPopover = null;
  markAboutHintSeen();
  popover.destroy();
}

const aboutDialog = initAboutDialog({
  dialogEl: document.getElementById("about-dialog"),
  openTriggers: [aboutOpenBtn],
  onOpen: () => dismissAboutHint(),
});

document.getElementById("about-guided-tour")?.addEventListener("click", (event) => {
  event.preventDefault();
  dismissAboutHint();
  aboutDialog?.closeDialog();
  overviewTour?.start();
});

if (aboutOpenBtn instanceof HTMLElement && !hasSeenAboutHint()) {
  aboutHintPopover = initPopover({
    anchor: aboutOpenBtn,
    body: "Check here for more info and a guided tour!",
    position: "right",
    dismissible: false,
    trapFocus: false,
    actions: [
      {
        label: "Got it",
        className: "btn btn-primary",
        closeOnClick: false,
        onClick: () => dismissAboutHint(),
      },
    ],
    onClose: () => {
      if (!aboutHintPopover) return;
      const popover = aboutHintPopover;
      aboutHintPopover = null;
      markAboutHintSeen();
      queueMicrotask(() => popover.destroy());
    },
  });
  // Let shell / layout settle before measuring the anchor.
  window.requestAnimationFrame(() => {
    aboutHintPopover?.open();
  });
}

initDialog({
  dialogEl: document.getElementById("info-dialog"),
  openTriggers: "#open-info-dialog",
});

const confirmDialog = initDialog({
  dialogEl: document.getElementById("confirm-dialog"),
  openTriggers: "#open-confirm-dialog",
});

document.getElementById("confirm-dialog-ok")?.addEventListener("click", () => {
  confirmDialog?.closeDialog();
});

const dangerDialog = initDialog({
  dialogEl: document.getElementById("danger-dialog"),
  openTriggers: "#open-danger-dialog",
});

document.getElementById("danger-dialog-ok")?.addEventListener("click", () => {
  dangerDialog?.closeDialog();
});

const bannerIds = [
  "demo-note-banner",
  "demo-info-banner",
  "demo-success-banner",
  "demo-important-banner",
  "demo-warning-banner",
  "demo-error-banner",
];

const rotatingBannerIds = new Set([
  "demo-note-banner",
  "demo-success-banner",
  "demo-important-banner",
  "demo-warning-banner",
]);

const bannerTriggers = [
  ["trigger-note-banner", "demo-note-banner"],
  ["trigger-info-banner", "demo-info-banner"],
  ["trigger-success-banner", "demo-success-banner"],
  ["trigger-important-banner", "demo-important-banner"],
  ["trigger-warning-banner", "demo-warning-banner"],
  ["trigger-error-banner", "demo-error-banner"],
];

const BANNER_TRIGGER_EXPIRE_MS = 3000;

function getBannerElements() {
  return bannerIds
    .map((id) => document.getElementById(id))
    .filter(Boolean);
}

function showBannerBriefly(bannerEl) {
  if (rotatingBannerIds.has(bannerEl.id)) {
    hideBanner(bannerEl);
  }
  showBanner(bannerEl, { expire: BANNER_TRIGGER_EXPIRE_MS });
}

for (const [buttonId, bannerId] of bannerTriggers) {
  document.getElementById(buttonId)?.addEventListener("click", () => {
    const bannerEl = document.getElementById(bannerId);
    if (!bannerEl) return;
    showBannerBriefly(bannerEl);
  });
}

document.getElementById("trigger-all-banners")?.addEventListener("click", () => {
  for (const banner of getBannerElements()) {
    showBannerBriefly(banner);
  }
});

document.getElementById("reset-banners")?.addEventListener("click", () => {
  for (const banner of getBannerElements()) {
    hideBanner(banner);
    showBanner(banner);
  }
});

for (const bannerId of rotatingBannerIds) {
  const bannerEl = document.getElementById(bannerId);
  if (bannerEl) showBanner(bannerEl);
}
